include nord.conf

font_family      JetBrains Mono Bold Italic
bold_font        JetBrains Mono ExtraBold Italic
italic_font      JetBrains Mono Bold Italic
bold_italic_font JetBrains Mono ExtraBold Italic

font_size 8

cursor #cccccc
cursor_shape beam
cursor_beam_thickness -1
cursor_blink_interval 0

window_padding_width 4
