include burgundy.conf

font_family      JetBrains Mono Light
bold_font        JetBrains Mono Bold
italic_font      JetBrains Mono Italic
bold_italic_font JetBrains Mono Bold Italic

font_size 14

cursor #cccccc
cursor_shape beam
cursor_beam_thickness -1
cursor_blink_interval 0

window_padding_width 4
