include kanagawa-dragon.conf

font_family      mononoki Italic Nerd Font Complete Mono
bold_font        mononoki Bold Nerd Font Complete Mono
italic_font      mononoki Italic Nerd Font Complete Mono
bold_italic_font mononoki Bold Italic Nerd Font Complete Mono

font_size 8

cursor #cccccc
cursor_shape beam
cursor_beam_thickness -1
cursor_blink_interval 0

window_padding_width 4
