cursor                  #928374
cursor_text_color       background

url_color               #83a598

visual_bell_color       #8ec07c
bell_border_color       #8ec07c

active_border_color     #d3869b
inactive_border_color   #665c54

foreground              #f2ead7
background              #1a0a16
selection_foreground    #928374
selection_background    #ebdbb2

active_tab_foreground   #fbf1c7
active_tab_background   #665c54
inactive_tab_foreground #a89984
inactive_tab_background #3c3836

# black  (bg3/bg4)
color0                  #1a0a16
color8                  #b2aa97

# red
color1                  #d11b2d
color9                  #d6154f

#: green
color2                  #8bf792
color10                 #ffa8b5

# yellow
color3                  #f2b600
color11                 #ff8e2b

# blue
color4                  #f29edd
color12                 #ed8d7c

# purple
color5                  #e3006a
color13                 #991667

# aqua
color6                  #ffabab
color14                 #f76c9a

# white (fg4/fg3)
color7                  #f2ead7
color15                 #e2dac7
