include sweetpastel.conf

font_family      JetBrains Mono Regular
bold_font        JetBrains Mono Regular
italic_font      JetBrains Mono Regular
bold_italic_font JetBrains Mono Regular

font_size 7

cursor #cccccc
cursor_shape beam
cursor_beam_thickness -1
cursor_blink_interval 0

window_padding_width 2
