#######################
### TMUX CONFIGURATION
#######################

# Global Settings
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:RGB"
bind r source-file ~/.config/tmux/tmux.conf \; display '~/.tmux.conf sourced'
setw -g automatic-rename on # Automatically rename windows
set -s escape-time 10       # Faster commands
set -g renumber-windows on  # Automatically renumber windows
set -g history-limit 5000   # Increase history limit
set -g status-interval 5    # Update status bar every 5 seconds
set -g mouse on             # Turn on mouse functionality

# Window Settings
bind -n M-H previous-window    # Go to window to the left
bind -n M-L next-window        # Go to window to the right
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

set -g @plugin 'rose-pine/tmux'
set -g @rose_pine_variant 'main' # Options are 'main', 'moon' or 'dawn'
set -g @rose_pine_host 'on'
set -g @rose_pine_date_time '%c' # %c is a good value but 
# You can insert as an option a value that the date command accepts (man date for info)
