#######################
### TMUX CONFIGURATION
#######################

# Global Settings
set -g default-terminal "alacritty"
bind r source-file ~/.config/tmux/tmux.conf \; display '~/.tmux.conf sourced'
setw -g automatic-rename on # Automatically rename windows
set -s escape-time 10       # Faster commands
set -g renumber-windows on  # Automatically renumber windows
set -g history-limit 5000   # Increase history limit
set -g status-interval 5    # Update status bar every 5 seconds
set -g mouse on             # Turn on mouse functionality

# Window Settings
bind -n M-Left previous-window # Go to window to the left
bind -n M-Right next-window    # Go to window to the right

# Plugins/Themes
set -g @plugin "plugins/freehdd"
#set -g @plugin "plugins/valleyofstars-theme"
set -g @plugin "plugins/hoodedpeak-theme"

# Set Plugin Options
set -g @freehdd_drive "$TMUXHDD"

# Run Tplug
run-shell ~/.config/tmux/tplug/tplug
