music_directory     "~/Music/"
playlist_directory  "~/Music/Playlists/"
db_file             "~/.config/mpd/mpd.db"
log_file            "~/.config/mpd/mpd.log"
pid_file            "~/.config/mpd/mpd.pid"
state_file          "~/.config/mpd/mpdstate"

user                "hpurdum"
bind_to_address     "any"

input {
        plugin "curl"
}

audio_output {  
        type  "alsa"  
        name  "mpd alsamixer-output"
        mixer_type "software"
}  

audio_output {  
        type               "fifo"  
        name               "fifo_visualizer"
        path               "/tmp/mpd.fifo"
        format             "44100:16:2"
}
